<?xml version="1.0"?>
<package format="3">
  <name>px4_vio_bridge</name>
  <version>0.1.0</version>
  <description>Bridge OAK-D Lite Basalt VIO poses into PX4 visual odometry over uXRCE-DDS.</description>
  <maintainer email="john@example.com">john</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <build_depend>nlohmann-json3-dev</build_depend>
  <depend>octomap</depend>
  <depend>octomap_msgs</depend>
  <depend>px4_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>rtabmap</depend>
  <depend>rtabmap_conversions</depend>
  <depend>rtabmap_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>

  <exec_depend>python3-psutil</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>foxglove_bridge</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
